-- Supabase Schema for ber.earth Blog Comments
-- Run this in your Supabase SQL Editor to set up the blog comment system

-- Create the blog comments table
CREATE TABLE blog_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id TEXT NOT NULL,
  name TEXT NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add comments for documentation
COMMENT ON TABLE blog_comments IS 'Blog comments for ber.earth website';
COMMENT ON COLUMN blog_comments.id IS 'Unique identifier for each comment';
COMMENT ON COLUMN blog_comments.post_id IS 'Blog post identifier to link comments to specific posts';
COMMENT ON COLUMN blog_comments.name IS 'Comment author display name';
COMMENT ON COLUMN blog_comments.message IS 'The comment content';
COMMENT ON COLUMN blog_comments.created_at IS 'When the comment was created';

-- Add indexes for better performance
CREATE INDEX idx_blog_comments_post_id ON blog_comments (post_id);
CREATE INDEX idx_blog_comments_created_at ON blog_comments (created_at DESC);

-- Enable Row Level Security (optional but recommended)
ALTER TABLE blog_comments ENABLE ROW LEVEL SECURITY;

-- Create policies for public access
-- Allow anyone to read blog comments
CREATE POLICY "Anyone can read blog comments" ON blog_comments
  FOR SELECT USING (true);

-- Allow anyone to insert blog comments
CREATE POLICY "Anyone can insert blog comments" ON blog_comments
  FOR INSERT WITH CHECK (true);

-- Enhanced server-side security pattern detection (no content filtering)
CREATE OR REPLACE FUNCTION prevent_blog_spam()
RETURNS TRIGGER AS $$
BEGIN
  -- Basic length validation
  IF LENGTH(TRIM(NEW.name)) < 1 OR LENGTH(TRIM(NEW.name)) > 100 THEN
    RAISE EXCEPTION 'Security: Comment author name must be between 1 and 100 characters';
  END IF;

  IF LENGTH(TRIM(NEW.message)) < 1 OR LENGTH(TRIM(NEW.message)) > 10000 THEN
    RAISE EXCEPTION 'Security: Comment message must be between 1 and 10000 characters';
  END IF;

  -- Basic post ID validation
  IF LENGTH(TRIM(NEW.post_id)) < 1 OR LENGTH(TRIM(NEW.post_id)) > 100 THEN
    RAISE EXCEPTION 'Security: Post ID must be between 1 and 100 characters';
  END IF;

  -- Technical security pattern detection (same as guestbook)

  -- URL patterns
  IF NEW.message ~* 'https?://[^\s]+' OR
     NEW.message ~* 'www\.[^\s]+' OR
     NEW.message ~* '[a-zA-Z0-9][a-zA-Z0-9-]{1,61}[a-zA-Z0-9]\.[a-zA-Z]{2,}' OR
     NEW.name ~* 'https?://[^\s]+' OR
     NEW.name ~* 'www\.[^\s]+' OR
     NEW.name ~* '[a-zA-Z0-9][a-zA-Z0-9-]{1,61}[a-zA-Z0-9]\.[a-zA-Z]{2,}' THEN
    RAISE EXCEPTION 'Security: URLs are not allowed';
  END IF;

  -- Email patterns
  IF NEW.message ~* '[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}' OR
     NEW.name ~* '[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}' THEN
    RAISE EXCEPTION 'Security: Email addresses are not allowed';
  END IF;

  -- Phone number patterns
  IF NEW.message ~* '\b\d{3}[-.]?\d{3}[-.]?\d{4}\b' OR
     NEW.message ~* '\+\d{1,3}[-.]?\d{3}[-.]?\d{3}[-.]?\d{4}\b' OR
     NEW.name ~* '\b\d{3}[-.]?\d{3}[-.]?\d{4}\b' OR
     NEW.name ~* '\+\d{1,3}[-.]?\d{3}[-.]?\d{3}[-.]?\d{4}\b' THEN
    RAISE EXCEPTION 'Security: Phone numbers are not allowed';
  END IF;

  -- SQL injection patterns
  IF NEW.message ~* '\b(UNION|SELECT|INSERT|UPDATE|DELETE|DROP|CREATE|ALTER|EXEC|SCRIPT)\b' OR
     NEW.message ~* '''\s*(OR|AND)\s*''\w*''\s*=\s*''\w*''' OR
     NEW.message ~* '\b(OR|AND)\s+\d+\s*=\s*\d+' OR
     NEW.name ~* '\b(UNION|SELECT|INSERT|UPDATE|DELETE|DROP|CREATE|ALTER|EXEC|SCRIPT)\b' OR
     NEW.name ~* '''\s*(OR|AND)\s*''\w*''\s*=\s*''\w*''' OR
     NEW.name ~* '\b(OR|AND)\s+\d+\s*=\s*\d+' THEN
    RAISE EXCEPTION 'Security: SQL injection attempts detected';
  END IF;

  -- XSS patterns
  IF NEW.message ~* 'javascript:' OR
     NEW.message ~* 'on\w+\s*=' OR
     NEW.message ~* '<\s*script' OR
     NEW.message ~* '<\s*iframe' OR
     NEW.name ~* 'javascript:' OR
     NEW.name ~* 'on\w+\s*=' OR
     NEW.name ~* '<\s*script' OR
     NEW.name ~* '<\s*iframe' THEN
    RAISE EXCEPTION 'Security: Potential XSS attack detected';
  END IF;

  -- HTML/BBCode tags
  IF NEW.message ~* '<[^>]*>' OR NEW.message ~* '\[[^\]]*\]' OR
     NEW.name ~* '<[^>]*>' OR NEW.name ~* '\[[^\]]*\]' THEN
    RAISE EXCEPTION 'Security: HTML/BBCode tags are not allowed';
  END IF;

  -- Markdown/Code blocks
  IF NEW.message ~* '```[\s\S]*?```' OR NEW.message ~* '`[^`]+`' OR
     NEW.name ~* '```[\s\S]*?```' OR NEW.name ~* '`[^`]+`' THEN
    RAISE EXCEPTION 'Security: Code blocks are not allowed';
  END IF;

  -- Excessive repeated characters (for readability only, more lenient)
  IF NEW.message ~* '([!?]){6,}' OR NEW.message ~* '(.)\1{7,}' OR
     NEW.name ~* '([!?]){6,}' OR NEW.name ~* '(.)\1{7,}' THEN
    RAISE EXCEPTION 'Security: Excessive character repetition detected';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger to run spam prevention
CREATE TRIGGER blog_comment_spam_prevention
  BEFORE INSERT ON blog_comments
  FOR EACH ROW EXECUTE FUNCTION prevent_blog_spam();

-- Grant necessary permissions
GRANT USAGE ON SCHEMA public TO anon;
GRANT ALL ON blog_comments TO anon;
GRANT USAGE, SELECT ON SEQUENCE blog_comments_id_seq TO anon;
