-- Supabase Schema for ber.earth Guestbook
-- Run this in your Supabase SQL Editor to set up the database

-- Create the guestbook entries table
CREATE TABLE guestbook_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  display_name TEXT NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add comments for documentation
COMMENT ON TABLE guestbook_entries IS 'Guestbook entries for ber.earth website';
COMMENT ON COLUMN guestbook_entries.id IS 'Unique identifier for each entry';
COMMENT ON COLUMN guestbook_entries.display_name IS 'Name displayed to other users';
COMMENT ON COLUMN guestbook_entries.message IS 'The guestbook message content';
COMMENT ON COLUMN guestbook_entries.created_at IS 'When the entry was created';

-- Add indexes for better performance
CREATE INDEX idx_guestbook_entries_created_at ON guestbook_entries (created_at DESC);

-- Enable Row Level Security (optional but recommended)
ALTER TABLE guestbook_entries ENABLE ROW LEVEL SECURITY;

-- Create policies for public access
-- Allow anyone to read guestbook entries
CREATE POLICY "Anyone can read guestbook entries" ON guestbook_entries
  FOR SELECT USING (true);

-- Allow anyone to insert guestbook entries
CREATE POLICY "Anyone can insert guestbook entries" ON guestbook_entries
  FOR INSERT WITH CHECK (true);

-- Enhanced server-side spam prevention function
CREATE OR REPLACE FUNCTION prevent_spam()
RETURNS TRIGGER AS $$
BEGIN
  -- Basic length validation
  IF LENGTH(TRIM(NEW.display_name)) < 1 OR LENGTH(TRIM(NEW.display_name)) > 100 THEN
    RAISE EXCEPTION 'Security: Display name must be between 1 and 100 characters';
  END IF;

  IF LENGTH(TRIM(NEW.message)) < 1 OR LENGTH(TRIM(NEW.message)) > 10000 THEN
    RAISE EXCEPTION 'Security: Message must be between 1 and 10000 characters';
  END IF;

  -- Technical security pattern detection (no content filtering)

  -- URL patterns
  IF NEW.message ~* 'https?://[^\s]+' OR
     NEW.message ~* 'www\.[^\s]+' OR
     NEW.message ~* '[a-zA-Z0-9][a-zA-Z0-9-]{1,61}[a-zA-Z0-9]\.[a-zA-Z]{2,}' OR
     NEW.display_name ~* 'https?://[^\s]+' OR
     NEW.display_name ~* 'www\.[^\s]+' OR
     NEW.display_name ~* '[a-zA-Z0-9][a-zA-Z0-9-]{1,61}[a-zA-Z0-9]\.[a-zA-Z]{2,}' THEN
    RAISE EXCEPTION 'Security: URLs are not allowed';
  END IF;

  -- Email patterns
  IF NEW.message ~* '[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}' OR
     NEW.display_name ~* '[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}' THEN
    RAISE EXCEPTION 'Security: Email addresses are not allowed';
  END IF;

  -- Phone number patterns
  IF NEW.message ~* '\b\d{3}[-.]?\d{3}[-.]?\d{4}\b' OR
     NEW.message ~* '\+\d{1,3}[-.]?\d{3}[-.]?\d{3}[-.]?\d{4}\b' OR
     NEW.display_name ~* '\b\d{3}[-.]?\d{3}[-.]?\d{4}\b' OR
     NEW.display_name ~* '\+\d{1,3}[-.]?\d{3}[-.]?\d{3}[-.]?\d{4}\b' THEN
    RAISE EXCEPTION 'Security: Phone numbers are not allowed';
  END IF;

  -- SQL injection patterns
  IF NEW.message ~* '\b(UNION|SELECT|INSERT|UPDATE|DELETE|DROP|CREATE|ALTER|EXEC|SCRIPT)\b' OR
     NEW.message ~* '''\s*(OR|AND)\s*''\w*''\s*=\s*''\w*''' OR
     NEW.message ~* '\b(OR|AND)\s+\d+\s*=\s*\d+' OR
     NEW.display_name ~* '\b(UNION|SELECT|INSERT|UPDATE|DELETE|DROP|CREATE|ALTER|EXEC|SCRIPT)\b' OR
     NEW.display_name ~* '''\s*(OR|AND)\s*''\w*''\s*=\s*''\w*''' OR
     NEW.display_name ~* '\b(OR|AND)\s+\d+\s*=\s*\d+' THEN
    RAISE EXCEPTION 'Security: SQL injection attempts detected';
  END IF;

  -- XSS patterns
  IF NEW.message ~* 'javascript:' OR
     NEW.message ~* 'on\w+\s*=' OR
     NEW.message ~* '<\s*script' OR
     NEW.message ~* '<\s*iframe' OR
     NEW.display_name ~* 'javascript:' OR
     NEW.display_name ~* 'on\w+\s*=' OR
     NEW.display_name ~* '<\s*script' OR
     NEW.display_name ~* '<\s*iframe' THEN
    RAISE EXCEPTION 'Security: Potential XSS attack detected';
  END IF;

  -- HTML/BBCode tags
  IF NEW.message ~* '<[^>]*>' OR NEW.message ~* '\[[^\]]*\]' OR
     NEW.display_name ~* '<[^>]*>' OR NEW.display_name ~* '\[[^\]]*\]' THEN
    RAISE EXCEPTION 'Security: HTML/BBCode tags are not allowed';
  END IF;

  -- Markdown/Code blocks
  IF NEW.message ~* '```[\s\S]*?```' OR NEW.message ~* '`[^`]+`' OR
     NEW.display_name ~* '```[\s\S]*?```' OR NEW.display_name ~* '`[^`]+`' THEN
    RAISE EXCEPTION 'Security: Code blocks are not allowed';
  END IF;

  -- Excessive repeated characters (for readability only, more lenient)
  IF NEW.message ~* '([!?]){6,}' OR NEW.message ~* '(.)\1{7,}' OR
     NEW.display_name ~* '([!?]){6,}' OR NEW.display_name ~* '(.)\1{7,}' THEN
    RAISE EXCEPTION 'Security: Excessive character repetition detected';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- (Optional) Create trigger to run spam prevention
CREATE TRIGGER guestbook_spam_prevention
  BEFORE INSERT ON guestbook_entries
  FOR EACH ROW EXECUTE FUNCTION prevent_spam();

-- Grant necessary permissions
GRANT USAGE ON SCHEMA public TO anon;
GRANT ALL ON guestbook_entries TO anon;
GRANT USAGE, SELECT ON SEQUENCE guestbook_entries_id_seq TO anon;
